"""create wallets transactions and exchange_rate_snapshots tables

Revision ID: a09e3a640dcd
Revises: 43fe6388989e
Create Date: 2026-07-06 11:07:15.880507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a09e3a640dcd'
down_revision: Union[str, Sequence[str], None] = '43fe6388989e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rate_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('quote_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(), server_default='frankfurter.dev', nullable=False),
    sa.CheckConstraint('rate > 0', name='ck_exchange_rate_snapshots_rate_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exchange_rate_snapshots_quote_currency_fetched_at', 'exchange_rate_snapshots', ['quote_currency', sa.literal_column('fetched_at DESC')], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance >= 0', name='ck_wallets_balance_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'currency', name='uq_wallets_user_id_currency')
    )
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('from_wallet_id', sa.UUID(), nullable=True),
    sa.Column('to_wallet_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('converted_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('to_currency', sa.String(length=3), nullable=True),
    sa.Column('from_rate_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('to_rate_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='completed', nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'completed', 'failed')", name='ck_transactions_status'),
    sa.CheckConstraint("type IN ('credit', 'debit', 'transfer')", name='ck_transactions_type'),
    sa.CheckConstraint('amount > 0', name='ck_transactions_amount_positive'),
    sa.ForeignKeyConstraint(['from_rate_snapshot_id'], ['exchange_rate_snapshots.id'], ),
    sa.ForeignKeyConstraint(['from_wallet_id'], ['wallets.id'], ),
    sa.ForeignKeyConstraint(['to_rate_snapshot_id'], ['exchange_rate_snapshots.id'], ),
    sa.ForeignKeyConstraint(['to_wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_transactions_from_wallet_id'), 'transactions', ['from_wallet_id'], unique=False)
    op.create_index('ix_transactions_from_wallet_id_created_at', 'transactions', ['from_wallet_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_transactions_to_wallet_id'), 'transactions', ['to_wallet_id'], unique=False)
    op.create_index('ix_transactions_to_wallet_id_created_at', 'transactions', ['to_wallet_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_to_wallet_id_created_at', table_name='transactions')
    op.drop_index(op.f('ix_transactions_to_wallet_id'), table_name='transactions')
    op.drop_index('ix_transactions_from_wallet_id_created_at', table_name='transactions')
    op.drop_index(op.f('ix_transactions_from_wallet_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index('ix_exchange_rate_snapshots_quote_currency_fetched_at', table_name='exchange_rate_snapshots')
    op.drop_table('exchange_rate_snapshots')
    # ### end Alembic commands ###
